//
// BehavioralAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class BehavioralAPI {

    /**
     Get behavioral coaching (Streamed)
     
     - parameter behavioralStreamRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    @discardableResult
    open class func behavioralAnswerPost(behavioralStreamRequest: BehavioralStreamRequest, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<String, ErrorResponse>) -> Void)) -> RequestTask {
        return behavioralAnswerPostWithRequestBuilder(behavioralStreamRequest: behavioralStreamRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(.success(response.body))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Get behavioral coaching (Streamed)
     - POST /behavioral/answer
     - Returns text/event-stream with chunks of feedback and improved answer.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter behavioralStreamRequest: (body)  
     - returns: RequestBuilder<String> 
     */
    open class func behavioralAnswerPostWithRequestBuilder(behavioralStreamRequest: BehavioralStreamRequest) -> RequestBuilder<String> {
        let localVariablePath = "/behavioral/answer"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: behavioralStreamRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
