//
// CodingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CodingAPI {

    /**
     Get coding assistance (Streamed)
     
     - parameter codingStreamRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    @discardableResult
    open class func codingAssistPost(codingStreamRequest: CodingStreamRequest, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<String, ErrorResponse>) -> Void)) -> RequestTask {
        return codingAssistPostWithRequestBuilder(codingStreamRequest: codingStreamRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(.success(response.body))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Get coding assistance (Streamed)
     - POST /coding/assist
     - Returns text/event-stream with reasoning and code.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter codingStreamRequest: (body)  
     - returns: RequestBuilder<String> 
     */
    open class func codingAssistPostWithRequestBuilder(codingStreamRequest: CodingStreamRequest) -> RequestBuilder<String> {
        let localVariablePath = "/coding/assist"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: codingStreamRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
