//
// BehavioralStreamRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BehavioralStreamRequest: Codable, JSONEncodable, Hashable {

    public var question: String
    public var context: String
    public var provider: String?
    public var sessionId: String?

    public init(question: String, context: String, provider: String? = nil, sessionId: String? = nil) {
        self.question = question
        self.context = context
        self.provider = provider
        self.sessionId = sessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case question
        case context
        case provider
        case sessionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(question, forKey: .question)
        try container.encode(context, forKey: .context)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
    }
}

