//
// SessionsPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionsPostRequest: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case behavioral = "behavioral"
        case coding = "coding"
    }
    public var title: String?
    public var type: ModelType?

    public init(title: String? = nil, type: ModelType? = nil) {
        self.title = title
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

