//
// SignUpRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignUpRequest: Codable, JSONEncodable, Hashable {

    public static let passwordRule = StringRule(minLength: 8, maxLength: nil, pattern: nil)
    public var email: String
    public var password: String
    public var fullName: String?

    public init(email: String, password: String, fullName: String? = nil) {
        self.email = email
        self.password = password
        self.fullName = fullName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case fullName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encodeIfPresent(fullName, forKey: .fullName)
    }
}

