//
// UserProfilePreferences.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserProfilePreferences: Codable, JSONEncodable, Hashable {

    public var saveSessionHistory: Bool?
    public var dataRetentionDays: Int?

    public init(saveSessionHistory: Bool? = nil, dataRetentionDays: Int? = nil) {
        self.saveSessionHistory = saveSessionHistory
        self.dataRetentionDays = dataRetentionDays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case saveSessionHistory
        case dataRetentionDays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(saveSessionHistory, forKey: .saveSessionHistory)
        try container.encodeIfPresent(dataRetentionDays, forKey: .dataRetentionDays)
    }
}

